apiVersion: apps/v1
kind: Deployment
metadata:
  name: oidc-auth
spec:
  template:
    spec:
      containers:
        - name: oidc-auth
          image: oidc-auth
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - secretRef:
                name: oidc-auth
          env:
            - name: HEADER_Authorization
              value: "join(' ', ['Bearer', raw])"
            - name: HEADER_X-Auth-Request-Subject
              value: "sub"
            - name: HEADER_X-Auth-Request-User
              value: "name"
            - name: HEADER_X-Auth-Request-Preferred-Username
              value: "preferred_username"
            - name: HEADER_X-Auth-Request-Email
              value: "email"
            - name: HEADER_X-Auth-Request-Groups
              value: "join(',', groups)"
            - name: DEFAULT_HEADERS
              value: Authorization,X-Auth-Request-Subject,X-Auth-Request-User,X-Auth-Request-Preferred-Username,X-Auth-Request-Email,X-Auth-Request-Groups
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "64Mi"
