apiVersion: apps/v1
kind: Deployment
metadata:
  name: oidc-auth
spec:
  template:
    spec:
      containers:
        - name: oidc-auth
          image: oidc-auth:1.14.2
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: oidc-auth
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "64Mi"
