apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- deployment.yaml

commonLabels:
  app.kubernetes.io/name: oidc-auth

images:
- name: oidc-auth
  newName: ghcr.io/ooraini/oidc-auth
  newTag: v0.4.0
